version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=weather
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - init_db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=weather
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - API_KEY=${API_KEY}

  init_db:
    build: .
    command: python init_db.py
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=weather
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres: